# règle pour nettoyer le répertoire
clean:
	$(REM) $(REMOPTS) *.o

# règle pour enlever tout fichiers autogénérés
mrproper: clean
	$(REM) $(REMOPTS) -f $(EXEC)
	$(REM) $(REMOPTS) -f $(EXEC).a

.PHONY: clean mrproper
